import BASICCompilerKit
import Foundation

/// Turns an imported Swift module into BASIC source (R4.2).
///
/// The generated text is ordinary BASIC — `CLASS`, fields, `FUNCTION`
/// signatures — so `IMPORT "Shapes"` reaches sema, BIR and the emitter along
/// the path every other import takes, and nothing downstream learns a new
/// concept. What marks these classes as *imported* is not their syntax but a
/// list the builder is handed (``externalClassNames``): their method bodies
/// are never emitted, because the framework already has them.
///
/// Method bodies here are placeholders that satisfy the parser and are
/// discarded. That is deliberate rather than lazy: a body the compiler
/// *keeps* would be a reimplementation of a framework method, and the first
/// time the two disagreed the program would run the wrong one.
public struct SwiftInterfaceUnit {
    /// The API this unit was generated from.
    public let api: SwiftAPI

    public init(api: SwiftAPI) {
        self.api = api
    }

    /// The BASIC type name a Swift class takes: its own, uppercased by the
    /// front end anyway.
    public static func basicName(of swiftName: String) -> String { swiftName }

    /// The generated source.
    public func render() -> String {
        var lines: [String] = [
            "' Generated by basicc from the symbol graph of \(api.module).",
            "' Every member below is the framework's own — the bodies here are",
            "' placeholders the compiler discards (see SwiftInterfaceUnit).",
        ]
        // BASIC's function types are named, so a `() -> Void` parameter needs
        // one declared before anything can mention it.
        if api.classes.contains(where: { $0.methods.contains { $0.parameters.contains { $0.type == .voidClosure } } }) {
            // `AS DOUBLE`, not VOID: a BASIC closure is an *expression* and
            // must yield something. Swift's `() -> Void` discards it, which
            // is the honest mapping — the handler is run for its effect.
            lines.append("FUNCTION TYPE \(Self.handlerType)() AS DOUBLE")
        }
        // Bases before subclasses, so INHERITS always names a declared class.
        for klass in ordered() {
            lines.append("CLASS \(klass.name)")
            if let superclass = klass.superclassPrecise, let base = api.class(precise: superclass) {
                lines.append("  INHERITS \(base.name)")
            }
            // BASIC has one constructor per class, spelled NEW; Swift may
            // have several. The first in graph order is the one imported and
            // the rest are reported, rather than picking silently by some
            // rule a reader would have to guess at.
            if let initializer = chosenInitializer(of: klass) {
                let parameters = initializer.parameters.map { "\($0.name) AS \(Self.basicType($0.type, in: api))" }
                    .joined(separator: ", ")
                lines.append("  FUNCTION New(\(parameters)) AS VOID")
                lines.append("  END FUNCTION")
            }
            for property in klass.properties {
                lines.append("  PUBLIC \(property.name) AS \(Self.basicType(property.type, in: api))")
            }
            for method in klass.methods {
                let parameters = method.parameters.map { "\($0.name) AS \(Self.basicType($0.type, in: api))" }
                    .joined(separator: ", ")
                if method.returns == .void {
                    lines.append("  FUNCTION \(method.name)(\(parameters)) AS VOID")
                    lines.append("  END FUNCTION")
                } else {
                    let type = Self.basicType(method.returns, in: api)
                    lines.append("  FUNCTION \(method.name)(\(parameters)) AS \(type)")
                    lines.append("    RETURN \(Self.placeholder(method.returns, in: api))")
                    lines.append("  END FUNCTION")
                }
            }
            lines.append("END CLASS")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// The initializer BASIC's `NEW` means: the first the graph lists whose
    /// parameters all have a BASIC spelling.
    public func chosenInitializer(of klass: SwiftAPI.Class) -> SwiftAPI.Function? {
        klass.initializers.first
    }

    /// Initializers not imported, because BASIC has one `NEW` per class.
    public var skippedInitializers: [SwiftAPI.Skip] {
        api.classes.flatMap { klass in
            klass.initializers.dropFirst().map {
                SwiftAPI.Skip(
                    member: "\(klass.name).init(\($0.parameters.map { ($0.label ?? "_") + ":" }.joined()))",
                    reason: "BASIC has one NEW per class and \(klass.name).init(\(chosenInitializer(of: klass)?.parameters.map { ($0.label ?? "_") + ":" }.joined() ?? "")) was imported"
                )
            }
        }
    }

    /// Classes with every base before its subclasses.
    public func ordered() -> [SwiftAPI.Class] {
        var out: [SwiftAPI.Class] = []
        var placed = Set<String>()
        func place(_ klass: SwiftAPI.Class) {
            guard !placed.contains(klass.precise) else { return }
            if let superclass = klass.superclassPrecise, let base = api.class(precise: superclass) { place(base) }
            placed.insert(klass.precise)
            out.append(klass)
        }
        for klass in api.classes { place(klass) }
        return out
    }

    /// Every class this unit declares, by the name BIR will know it under.
    public var externalClassNames: [String] {
        api.classes.map { $0.name.uppercased() }
    }

    /// What was imported and what was not, per framework (R4.8).
    ///
    /// The tripwire against silent rot: a binding layer that loses half a
    /// framework looks exactly like one that never had it, unless something
    /// counts. Printed by `basicc import-report`.
    public func report() -> String {
        var lines = ["\(api.module): \(api.classes.count) class(es)"]
        for klass in ordered() {
            var parts: [String] = []
            if let base = klass.superclassPrecise.flatMap({ self.api.class(precise: $0) }) { parts.append("inherits \(base.name)") }
            parts.append("\(klass.properties.count) propert\(klass.properties.count == 1 ? "y" : "ies")")
            parts.append("\(klass.methods.count) method(s)")
            if let initializer = chosenInitializer(of: klass) {
                parts.append("NEW(\(initializer.parameters.map(\.name).joined(separator: ", ")))")
            } else {
                parts.append("no NEW")
            }
            lines.append("  \(klass.name) — " + parts.joined(separator: ", "))
        }
        let skips = api.skipped + skippedInitializers
        if skips.isEmpty {
            lines.append("  nothing skipped")
        } else {
            lines.append("  skipped \(skips.count):")
            for skip in skips.sorted(by: { $0.member < $1.member }) {
                lines.append("    \(skip.member) — \(skip.reason)")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// The name of the generated function type a `() -> Void` parameter
    /// takes. One per unit, because every such parameter is the same shape.
    public static let handlerType = "SwiftHandler"

    static func basicType(_ type: SwiftAPI.ValueType, in api: SwiftAPI) -> String {
        switch type {
        // A Swift `Int` is a BASIC number too: the interpreter keeps every
        // number as a Double, and INTEGER is a declaration, not a machine
        // width. Conversion happens at the boundary.
        case .double, .int: return "DOUBLE"
        case .bool: return "BOOLEAN"
        case .string: return "STRING"
        case .object(let precise): return api.class(precise: precise)?.name ?? "VARIANT"
        // A handler BASIC hands over; the generated unit declares it as the
        // language's own function type.
        case .voidClosure: return handlerType
        case .void, .unsupported: return "VOID"
        }
    }

    /// A value of the right type for a placeholder body.
    static func placeholder(_ type: SwiftAPI.ValueType, in api: SwiftAPI) -> String {
        switch type {
        case .double, .int: return "0"
        case .bool: return "FALSE"
        case .string: return "\"\""
        case .object(let precise): return "NEW \(api.class(precise: precise)?.name ?? "VARIANT")"
        case .void, .voidClosure, .unsupported: return "0"
        }
    }
}
