import Foundation

/// Swift source that lets a compiled BASIC program call an imported `async`
/// method (R3.3).
///
/// ## Why this is generated Swift rather than emitted IR
///
/// Everything else `basicc` imports is called by its mangled symbol straight
/// from emitted IR, because an ordinary Swift function is an ordinary call.
/// An `async` function is not: its ABI is a context pointer and a
/// continuation, and reaching it means creating a task and resuming it — work
/// the Swift runtime does through code the compiler generates, not through a
/// call anyone can hand-write.
///
/// So for these, and only these, `basicc` writes a few lines of Swift and
/// compiles them against the framework. The shim starts a **real task**,
/// which really suspends, and waits for it — so the concurrency is Swift's,
/// and BASIC's side of the call blocks, which is what `AWAIT` already means
/// in the interpreter.
///
/// ## What it is not
///
/// It is not a bridge object, and it is not a reimplementation of anything.
/// Each shim is a `@_cdecl` wrapper of one method: unwrap the receiver, start
/// the task, wait, hand back the value.
public struct SwiftAsyncShim {
    /// One method that needs a shim.
    public struct Method: Sendable {
        /// The class the method is on.
        public let className: String
        /// The method's Swift name.
        public let name: String
        /// Its argument labels, in order, for the call.
        public let labels: [String?]
        /// The Swift spelling of each parameter type.
        public let parameterTypes: [String]
        /// The Swift spelling of the result, or nil for `Void`.
        public let returns: String?
        /// Whether it also throws.
        public let isThrowing: Bool
        /// Whether it is awaited, or merely takes a handler (R4.5).
        public var isAsync: Bool = true
        /// Which parameters are `() -> Void` handlers.
        public var closureParameters: Set<Int> = []
        /// Which parameters are class references, by the class's Swift name.
        ///
        /// A `@_cdecl` function cannot mention a Swift class that is not
        /// `@objc`, so these cross as pointers and are bridged here — the
        /// same way the receiver always has.
        public var objectParameters: [Int: String] = [:]
        /// The class this returns, when it returns one.
        public var objectResult: String?

        public init(className: String, name: String, labels: [String?],
                    parameterTypes: [String], returns: String?, isThrowing: Bool) {
            self.className = className
            self.name = name
            self.labels = labels
            self.parameterTypes = parameterTypes
            self.returns = returns
            self.isThrowing = isThrowing
        }

        /// The C symbol the emitted IR calls.
        public var symbol: String {
            (isAsync ? "basic_await_" : "basic_handler_") + "\(className)_\(name)"
        }
    }

    /// The module being imported.
    public let module: String
    /// Its async methods.
    public let methods: [Method]

    public init(module: String, methods: [Method]) {
        self.module = module
        self.methods = methods
    }

    /// The Swift source, or nil when there is nothing to shim.
    public func source() -> String? {
        guard !methods.isEmpty else { return nil }
        var lines = [
            "// Generated by basicc so a BASIC program can await \(module)'s",
            "// async methods. Nothing here is hand-written; see SwiftAsyncShim.",
            "import Foundation",
            "import \(module)",
            "",
            "/// The runtime's error raiser, declared by symbol rather than",
            "/// imported: the shim compiles against the *framework*, and adding",
            "/// BASICRTSwift to its search path would tie a generated file to",
            "/// wherever the compiler happens to be installed.",
            "@_silgen_name(\"basic_rt_swift_error_raise\")",
            "private func basicAwaitRaise(_ error: Error) -> Never",
            "",
            "/// Carries a result out of the task that produced it.",
            "private final class BASICAwaitBox<Value>: @unchecked Sendable {",
            "    var value: Value?",
            "    var failure: Error?",
            "}",
            "",
            "/// Runs `body` as a real task and waits for it.",
            "///",
            "/// The suspension is Swift's — the task really suspends and really",
            "/// resumes. The waiting is BASIC's, which is what `AWAIT` means",
            "/// there: the statement does not finish until the value is in hand.",
            "private func basicAwait<Value>(_ body: @escaping @Sendable () async throws -> Value) throws -> Value {",
            "    let box = BASICAwaitBox<Value>()",
            "    let semaphore = DispatchSemaphore(value: 0)",
            "    Task.detached {",
            "        do { box.value = try await body() } catch { box.failure = error }",
            "        semaphore.signal()",
            "    }",
            "    semaphore.wait()",
            "    if let failure = box.failure { throw failure }",
            "    return box.value!",
            "}",
            "",
        ]
        for method in methods {
            // A handler parameter arrives as the pair BASIC can supply — a C
            // function pointer and the closure it should invoke — and becomes
            // an ordinary Swift closure right here, which is the whole point:
            // the framework stores a Swift closure, not a wrapper object.
            var parameters = ["_ me: UnsafeMutableRawPointer"]
            var callArguments: [String] = []
            for (index, type) in method.parameterTypes.enumerated() {
                if method.closureParameters.contains(index) {
                    parameters.append("_ fn\(index): @convention(c) (UnsafeMutableRawPointer?) -> Void")
                    parameters.append("_ ctx\(index): UnsafeMutableRawPointer?")
                    callArguments.append("{ fn\(index)(ctx\(index)) }")
                } else if method.objectParameters[index] != nil {
                    parameters.append("_ a\(index): UnsafeMutableRawPointer")
                    // Bridged before the call, never inside the task's
                    // closure: capturing a raw pointer there is a concurrency
                    // error in Swift 6, and the object reference is what the
                    // call wants anyway.
                    callArguments.append("o\(index)")
                } else {
                    parameters.append("_ a\(index): \(type)")
                    callArguments.append("a\(index)")
                }
            }
            let labelled = zip(method.labels, callArguments.indices)
                .map { label, index in label.map { "\($0): \(callArguments[index])" } ?? callArguments[index] }
                .joined(separator: ", ")
            // A class result crosses as a pointer too, unretained: an
            // imported object belongs to the framework, and BASIC holding one
            // aliases it rather than owning a copy (ruling D15).
            let result = method.objectResult != nil
                ? " -> UnsafeMutableRawPointer"
                : (method.returns.map { " -> \($0)" } ?? "")
            func handOut(_ expression: String) -> String {
                method.objectResult != nil ? "Unmanaged.passUnretained(\(expression)).toOpaque()" : expression
            }
            lines.append("@_cdecl(\"\(method.symbol)\")")
            lines.append("public func \(method.symbol)(\(parameters.joined(separator: ", ")))\(result) {")
            lines.append("    let object = Unmanaged<\(method.className)>.fromOpaque(me).takeUnretainedValue()")
            for (index, className) in method.objectParameters.sorted(by: { $0.key < $1.key }) {
                lines.append("    let o\(index) = Unmanaged<\(className)>.fromOpaque(a\(index)).takeUnretainedValue()")
            }
            if method.isAsync {
                let awaited = method.isThrowing
                    ? "try await object.\(method.name)(\(labelled))"
                    : "await object.\(method.name)(\(labelled))"
                lines.append("    do {")
                if method.returns == nil {
                    lines.append("        _ = try basicAwait { \(awaited) }")
                } else {
                    lines.append("        return \(handOut("try basicAwait { \(awaited) }"))")
                }
                lines.append("    } catch {")
                lines.append("        basicAwaitRaise(error)")
                lines.append("    }")
            } else if method.isThrowing {
                lines.append("    do {")
                let called = "try object.\(method.name)(\(labelled))"
                lines.append(method.returns == nil ? "        _ = \(called)" : "        return \(handOut(called))")
                lines.append("    } catch {")
                lines.append("        basicAwaitRaise(error)")
                lines.append("    }")
            } else {
                // **`MainActor.assumeIsolated`, and it is load-bearing.** A
                // UI framework's API is usually `@MainActor`-isolated, and a
                // `@_cdecl` entry point is nonisolated — so calling one from
                // the other is refused outright. A compiled BASIC program
                // runs its statements on the main thread, so the assertion is
                // true; stating it is what lets a main-actor framework be
                // imported at all. It traps rather than corrupts if a future
                // caller is ever elsewhere.
                let called = "object.\(method.name)(\(labelled))"
                if method.returns == nil {
                    lines.append("    MainActor.assumeIsolated { \(called) }")
                } else {
                    lines.append("    return MainActor.assumeIsolated { \(handOut(called)) }")
                }
            }
            lines.append("}")
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }
}
