import BASICCompilerKit
import Foundation

/// Turns an imported Swift module into BASIC source (R4.2).
///
/// The generated text is ordinary BASIC — `CLASS`, fields, `FUNCTION`
/// signatures — so `IMPORT "Shapes"` reaches sema, BIR and the emitter along
/// the path every other import takes, and nothing downstream learns a new
/// concept. What marks these classes as *imported* is not their syntax but a
/// list the builder is handed (``externalClassNames``): their method bodies
/// are never emitted, because the framework already has them.
///
/// Method bodies here are placeholders that satisfy the parser and are
/// discarded. That is deliberate rather than lazy: a body the compiler
/// *keeps* would be a reimplementation of a framework method, and the first
/// time the two disagreed the program would run the wrong one.
public struct SwiftInterfaceUnit {
    /// The API this unit was generated from.
    public let api: SwiftAPI

    public init(api: SwiftAPI) {
        self.api = api
    }

    /// The BASIC type name a Swift class takes: its own, uppercased by the
    /// front end anyway.
    public static func basicName(of swiftName: String) -> String { swiftName }

    /// The generated source.
    public func render() -> String {
        var lines: [String] = [
            "' Generated by basicc from the symbol graph of \(api.module).",
            "' Every member below is the framework's own — the bodies here are",
            "' placeholders the compiler discards (see SwiftInterfaceUnit).",
        ]
        // BASIC's function types are named, so a `() -> Void` parameter needs
        // one declared before anything can mention it.
        // Every protocol a signature actually names becomes an INTERFACE,
        // and the classes the graph says conform declare IMPLEMENTS. Only the
        // ones that are used: declaring all of a framework's protocols would
        // fill the unit with names no program can reach.
        for precise in Self.protocolsUsed(in: api).sorted() {
            guard let name = api.protocols[precise] else { continue }
            lines.append("INTERFACE \(name)")
            lines.append("END INTERFACE")
        }
        if api.classes.contains(where: { $0.methods.contains { $0.parameters.contains { $0.type == .voidClosure } } }) {
            // `AS DOUBLE`, not VOID: a BASIC closure is an *expression* and
            // must yield something. Swift's `() -> Void` discards it, which
            // is the honest mapping — the handler is run for its effect.
            lines.append("FUNCTION TYPE \(Self.handlerType)() AS DOUBLE")
        }
        // Bases before subclasses, so INHERITS always names a declared class.
        for klass in ordered() {
            lines.append("CLASS \(klass.name)")
            if let superclass = klass.superclassPrecise, let base = api.class(precise: superclass) {
                lines.append("  INHERITS \(base.name)")
            }
            for precise in (api.conformances[klass.precise] ?? []).sorted()
            where Self.protocolsUsed(in: api).contains(precise) {
                if let name = api.protocols[precise] { lines.append("  IMPLEMENTS \(name)") }
            }
            // BASIC has one constructor per class, spelled NEW; Swift may
            // have several. The first in graph order is the one imported and
            // the rest are reported, rather than picking silently by some
            // rule a reader would have to guess at.
            if let initializer = chosenInitializer(of: klass) {
                let parameters = Self.declared(initializer.passed, in: api)
                    .joined(separator: ", ")
                lines.append("  FUNCTION New(\(parameters)) AS VOID")
                lines.append("  END FUNCTION")
            }
            for property in klass.properties {
                lines.append("  PUBLIC \(property.name) AS \(Self.basicType(property.type, in: api))")
            }
            for method in klass.methods {
                let parameters = Self.declared(method.passed, in: api)
                    .joined(separator: ", ")
                if method.returns == .void {
                    lines.append("  FUNCTION \(method.name)(\(parameters)) AS VOID")
                    lines.append("  END FUNCTION")
                } else {
                    let type = Self.basicType(method.returns, in: api)
                    lines.append("  FUNCTION \(method.name)(\(parameters)) AS \(type)")
                    lines.append("    RETURN \(Self.placeholder(method.returns, in: api))")
                    lines.append("  END FUNCTION")
                }
            }
            lines.append("END CLASS")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// The initializer BASIC's `NEW` means: the first the graph lists whose
    /// parameters all have a BASIC spelling.
    public func chosenInitializer(of klass: SwiftAPI.Class) -> SwiftAPI.Function? {
        klass.initializers.first
    }

    /// Initializers not imported, because BASIC has one `NEW` per class.
    public var skippedInitializers: [SwiftAPI.Skip] {
        api.classes.flatMap { klass in
            klass.initializers.dropFirst().map {
                SwiftAPI.Skip(
                    member: "\(klass.name).init(\($0.parameters.map { ($0.label ?? "_") + ":" }.joined()))",
                    reason: "BASIC has one NEW per class and \(klass.name).init(\(chosenInitializer(of: klass)?.parameters.map { ($0.label ?? "_") + ":" }.joined() ?? "")) was imported"
                )
            }
        }
    }

    /// Classes with every base before its subclasses.
    public func ordered() -> [SwiftAPI.Class] {
        var out: [SwiftAPI.Class] = []
        var placed = Set<String>()
        func place(_ klass: SwiftAPI.Class) {
            guard !placed.contains(klass.precise) else { return }
            if let superclass = klass.superclassPrecise, let base = api.class(precise: superclass) { place(base) }
            placed.insert(klass.precise)
            out.append(klass)
        }
        for klass in api.classes { place(klass) }
        return out
    }

    /// Every class this unit declares, by the name BIR will know it under.
    public var externalClassNames: [String] {
        api.classes.map { $0.name.uppercased() }
    }

    /// What was imported and what was not, per framework (R4.8).
    ///
    /// The tripwire against silent rot: a binding layer that loses half a
    /// framework looks exactly like one that never had it, unless something
    /// counts. Printed by `basicc import-report`.
    public func report() -> String {
        var lines = ["\(api.module): \(api.classes.count) class(es)"]
        for klass in ordered() {
            var parts: [String] = []
            if let base = klass.superclassPrecise.flatMap({ self.api.class(precise: $0) }) { parts.append("inherits \(base.name)") }
            parts.append("\(klass.properties.count) propert\(klass.properties.count == 1 ? "y" : "ies")")
            parts.append("\(klass.methods.count) method(s)")
            if let initializer = chosenInitializer(of: klass) {
                parts.append("NEW(\(Self.names(initializer.passed, in: api).joined(separator: ", ")))")
            } else {
                parts.append("no NEW")
            }
            lines.append("  \(klass.name) — " + parts.joined(separator: ", "))
        }
        let skips = api.skipped + skippedInitializers
        if skips.isEmpty {
            lines.append("  nothing skipped")
        } else {
            lines.append("  skipped \(skips.count):")
            for skip in skips.sorted(by: { $0.member < $1.member }) {
                lines.append("    \(skip.member) — \(skip.reason)")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// The name of the generated function type a `() -> Void` parameter
    /// takes. One per unit, because every such parameter is the same shape.
    public static let handlerType = "SwiftHandler"

    /// The protocols any imported signature names.
    static func protocolsUsed(in api: SwiftAPI) -> Set<String> {
        var used = Set<String>()
        for klass in api.classes {
            for function in klass.methods + klass.initializers {
                for parameter in function.parameters {
                    if case .protocolType(let precise) = parameter.type { used.insert(precise) }
                }
            }
        }
        return used
    }

    /// A parameter list as BASIC declares it.
    ///
    /// A struct becomes one parameter per scalar it flattens to — `frame` is
    /// `frame_x, frame_y, frame_width, frame_height` — because BASIC has no
    /// name for the struct and the shim rebuilds it from exactly these, in
    /// this order.
    static func declared(_ parameters: [SwiftAPI.Parameter], in api: SwiftAPI) -> [String] {
        zip(names(parameters, in: api), types(parameters, in: api))
            .map { "\($0) AS \($1)" }
    }

    static func names(_ parameters: [SwiftAPI.Parameter], in api: SwiftAPI) -> [String] {
        parameters.flatMap { parameter -> [String] in
            guard case .structure = parameter.type, let leaves = leafNames(of: parameter.type, in: api) else {
                return [parameter.name]
            }
            return leaves.map { "\(parameter.name)_\($0)" }
        }
    }

    static func types(_ parameters: [SwiftAPI.Parameter], in api: SwiftAPI) -> [String] {
        parameters.flatMap { parameter -> [String] in
            guard case .structure = parameter.type, let leaves = api.leaves(of: parameter.type) else {
                return [basicType(parameter.type, in: api)]
            }
            return leaves.map { basicType($0, in: api) }
        }
    }

    /// The dotted names of a struct's leaves, so a parameter reads
    /// `frame_origin_x` rather than `frame_0`.
    static func leafNames(of type: SwiftAPI.ValueType, in api: SwiftAPI, depth: Int = 0) -> [String]? {
        guard depth < 8, case .structure(let precise) = type,
              let structure = api.structures[precise], !structure.fields.isEmpty else { return nil }
        var out: [String] = []
        for field in structure.fields {
            if case .structure = field.type {
                guard let inner = leafNames(of: field.type, in: api, depth: depth + 1) else { return nil }
                out += inner.map { "\(field.name)_\($0)" }
            } else {
                out.append(field.name)
            }
        }
        return out
    }

    static func basicType(_ type: SwiftAPI.ValueType, in api: SwiftAPI) -> String {
        switch type {
        // A Swift `Int` is a BASIC number too: the interpreter keeps every
        // number as a Double, and INTEGER is a declaration, not a machine
        // width. Conversion happens at the boundary.
        case .double, .int: return "DOUBLE"
        case .bool: return "BOOLEAN"
        case .string: return "STRING"
        case .object(let precise): return api.class(precise: precise)?.name ?? "VARIANT"
        // A handler BASIC hands over; the generated unit declares it as the
        // language's own function type.
        // Flattened at the call, so it never names a BASIC type of its own.
        case .structure: return "DOUBLE"
        // An INTERFACE, declared by the unit; any conforming imported class
        // may be passed where one is wanted.
        case .protocolType(let precise): return api.protocols[precise] ?? "VARIANT"
        // A BASIC array travels in a VARIANT — that is how a function hands
        // one back in this language, and `LEN(v)` and `v(i)` walk it.
        case .array: return "VARIANT"
        case .voidClosure: return handlerType
        case .void, .unsupported: return "VOID"
        }
    }

    /// A value of the right type for a placeholder body.
    static func placeholder(_ type: SwiftAPI.ValueType, in api: SwiftAPI) -> String {
        switch type {
        case .double, .int: return "0"
        case .bool: return "FALSE"
        case .string: return "\"\""
        case .object(let precise):
            // The body is discarded, but it still has to type-check — and a
            // class whose NEW takes arguments will not accept none. Zeros of
            // the right arity; `EMPTY` when the class has no NEW to call.
            guard let klass = api.class(precise: precise) else { return "EMPTY" }
            // A class with no importable NEW still constructs the BASIC way,
            // with default fields — `EMPTY` is not a value of a class type.
            guard let initializer = klass.initializers.first else { return "NEW \(klass.name)" }
            // A zero of the *right kind* for each argument — `0` for a
            // number, `""` for a string — because the placeholder still has
            // to type-check even though nothing ever runs it.
            let arguments = types(initializer.passed, in: api).map { basic -> String in
                switch basic {
                case "STRING": return "\"\""
                case "BOOLEAN": return "FALSE"
                case handlerType: return "FUNCTION() AS DOUBLE = 0"
                default: return "0"
                }
            }
            guard !arguments.isEmpty else { return "NEW \(klass.name)" }
            return "NEW \(klass.name)(\(arguments.joined(separator: ", ")))"
        // A placeholder body is discarded, but it still has to type-check,
        // and EMPTY is the VARIANT with nothing in it.
        case .array: return "EMPTY"
        case .void, .voidClosure, .structure, .protocolType, .unsupported: return "0"
        }
    }
}
